# Generated by Django 6.1.1 on 2026-09-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_total_alter_orderitem_line_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Card"),
                    ("bank_transfer", "Bank transfer"),
                    ("cash_on_delivery", "Cash on delivery"),
                ],
                default="card",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.CharField(default="", max_length=500),
        ),
    ]
