# Generated by Django 6.1.1 on 2026-09-26

from django.db import migrations, models


def migrate_paid_orders(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Order.objects.filter(status="paid").update(
        status="processing", payment_status="paid"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_payment_method_order_shipping_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate_paid_orders, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
