# Generated by Django 6.1.1 on 2026-09-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_payment_status_separate_payment_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_provider",
            field=models.CharField(
                blank=True,
                choices=[("mercadopago", "Mercado Pago")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="provider_payment_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="provider_preference_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
