# Generated by Django 6.1.1 on 2026-09-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_order_payment_provider_order_provider_payment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
