# Generated by Django 6.1.1 on 2026-09-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_order_payment_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="provider_checkout_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
